In [1]:
import numpy as np
import pandas as pd
import sys
import time

In [4]:
a=np.array([[1,-3,3],[3,-5,3],[6,-6,4]])
print(a)

[[ 1 -3  3]
 [ 3 -5  3]
 [ 6 -6  4]]


In [8]:
a1=a.transpose()
print(a1)

[[ 1  3  6]
 [-3 -5 -6]
 [ 3  3  4]]


In [9]:
x=a1.dot(a)
print(x)

[[ 46 -54  36]
 [-54  70 -48]
 [ 36 -48  34]]


In [10]:
#finding eigenvalues
from numpy import array
from numpy.linalg import eig

In [19]:
#define matrix
A = array([[-2,-4,2],[-2 ,1 ,2],[4,2,5]])

In [20]:
print(A)

[[-2 -4  2]
 [-2  1  2]
 [ 4  2  5]]


In [21]:
#FACTORIZE
vals, vectors = eig(A)

In [22]:
print(vals)
print(vectors)

[-5.  3.  6.]
[[ 0.81649658  0.53452248  0.05842062]
 [ 0.40824829 -0.80178373  0.35052374]
 [-0.40824829 -0.26726124  0.93472998]]
