In [4]:
# singular value decomposition
from numpy import array
from scipy.linalg import svd

In [5]:
#define a matrix
A= array([[3,1,1],[-1,3,1]])
print(A)

[[ 3  1  1]
 [-1  3  1]]


In [7]:
#factorize
U, s, V = svd(A)
print(U)
print(s)
print(V)

[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
[3.46410162 3.16227766]
[[-4.08248290e-01 -8.16496581e-01 -4.08248290e-01]
 [-8.94427191e-01  4.47213595e-01  5.27355937e-16]
 [-1.82574186e-01 -3.65148372e-01  9.12870929e-01]]


In [9]:
#finding the left singular matrix(U)
import numpy as np
from numpy.linalg import eig
values1, vectors1 = eig(np.dot(A,A.T))

In [10]:
values1 #lowest value ignored hence 0 is not shown in the matrix

array([12., 10.])

In [11]:
vectors1

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [13]:
#finding the right singular matrix(V)
import numpy as np
from numpy.linalg import eig
values2, vectors2 = eig(np.dot(A.T,A))

In [14]:
print(values2)

[ 0. 10. 12.]


In [15]:
print(vectors2)

[[ 1.82574186e-01 -8.94427191e-01 -4.08248290e-01]
 [ 3.65148372e-01  4.47213595e-01 -8.16496581e-01]
 [-9.12870929e-01  5.07702013e-16 -4.08248290e-01]]


In [16]:
sigma=np.diag(values1)

In [ ]:
#singular value decomposition
from numpy import array
